apiVersion: training.eduk8s.io/v1alpha1
kind: Workshop
metadata:
  name: lab-spring-boot
spec:
  vendor: eduk8s.io
  title: Getting Started with Spring Boot
  description: Create a Spring Boot application and deploy it to Kubernetes
  url: https://github.com/scratches/lab-spring-boot
  #image: dsyer/lab-spring-boot:master
  content: github.com/scratches/lab-spring-boot
  duration: 15m
  image: dsyer/ws
  session:
    budget: small
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
      editor:
        enabled: true
      registry:
        enabled: true
      docker:
        enabled: true
